### ISSUE TITLE
"Companion metadata file" with OME-XML allowed? 

### ISSUE THREAD

**Issue by robertgiessmann** [ome/ome-model#146]
Hi there! 

I read https://docs.openmicroscopy.org/ome-model/6.0.0/specifications/minimum.html and read about a "<MetadataOnly/>" element. That sounds to me like it would be allowed to put an OME-XML file next to some tiff files to describe them? I am not sure whether I got that right, sorry for the newbie question.

Would be great if you could help me out here. :) Thanks!

**Comment by sbesson** [comment]
Hi @robertgiessmann,

no worries, that's why GitHub issues are here. What you are looking for is more formally described in [this section](https://docs.openmicroscopy.org/ome-model/latest/ome-tiff/specification.html#partial-ome-xml-metadata) of the OME-TIFF specification i.e. the ability to externalize the OME-XML metadata outside the `ImageDescription` tag.

It is possible to use ancillary files containing this metadata, the main requirement is that these files should be suffixed with `.companion.ome`. There are a few public examples described [here](https://docs.openmicroscopy.org/ome-model/6.2.0/ome-tiff/data.html#multifile-samples) which should help you getting started.

Let us know if you need more information
