### ISSUE TITLE
404 URL in ome.xsd

### ISSUE THREAD

**Issue by joshmoore** [ome/ome-model#179]
https://github.com/ome/ome-model/blob/fbe39c099b4b3ab02ccfa93c0af6bcf84515a564/specification/src/main/resources/released-schema/2016-06/ome.xsd#L3186C15-L3186C15 points to http://www.openmicroscopy.org/site/support/file-formats/working-with-ome-xml/id-and-lsid which no longer resolves

**Comment by sbesson** [comment]
https://github.com/ome/prod-playbooks/blob/4687065e26c009e2012e0752b2b8bf17f3e4af56/www/www-deploy.yml#L198-L201 defines the current redirects for this domain. Two comments:

- since this page has been renamed as https://ome-model.readthedocs.io/en/latest/developers/id-and-lsid.html, I think it will require a specific redirect entry
- the redirects only apply to the root directory so it might worth adding something along the lines of https://github.com/ome/prod-playbooks/blob/4687065e26c009e2012e0752b2b8bf17f3e4af56/www/www-deploy.yml#L196-L197

**Comment by jburel** [comment]
Fixed
